/**
 * Created with JetBrains WebStorm.
 * User: stan229
 * Date: 9/19/12
 * Time: 3:35 PM
 * To change this template use File | Settings | File Templates.
 */
Ext.define('D3Mobile.view.hero.Attributes', {
    extend   : 'Ext.Container',
    xtype    : 'attributes',
    requires : ['D3Mobile.view.hero.Header'],
    config   : {
        cls              : 'hero-detail-card',
        scrollable       : {
            direction     : 'vertical',
            directionLock : true
        },
        styleHtmlContent : true,
        header           : {},
        headerLabel      : 'Attributes',
        tpl              : ''.concat(
            '<div class="hero-attributes">',
                '<tpl if="statDeltas.lastUpdated">',
                    '<div class="last-updated">',
                        'Stat changes since {statDeltas.lastUpdated}',
                    '</div>',
                '</tpl>',
                '<div class="base-stats">',
                    '<div class="stats-group">',
                        '<div class="stats-row highlight">',
                            '<div class="attribute-label">Elite Kills</div>',
                            '<div class="attribute-value">{kills.elites}</div>',
                        '</div>',
                        '<div class="stats-row">',
                            '<div class="attribute-label">Damage</div>',
                            '<div class="attribute-value">{[values.stats.damage.toFixed(0)]}',
                                '<tpl if="statDeltas.damage">',
                                    '<tpl if="statDeltas.damage &gt; 0">',
                                        '<span class="change d3-color-green">+{[values.statDeltas.damage.toFixed(0)]}</span>',
                                    '<tpl else>',
                                        '<span class="change d3-color-red">{[values.statDeltas.damage.toFixed(0)]}</span>',
                                    '</tpl>',
                                '</tpl>',
                            '</div>',
                        '</div>',
                        '<div class="stats-row">',
                            '<div class="attribute-label">Life</div>',
                            '<div class="attribute-value">{stats.life}',
                                '<tpl if="statDeltas.life">',
                                    '<tpl if="statDeltas.life &gt; 0">',
                                        '<span class="change d3-color-green">+{statDeltas.life}</span>',
                                    '<tpl else>',
                                        '<span class="change d3-color-red">{statDeltas.life}</span>',
                                    '</tpl>',
                                '</tpl>',
                            '</div>',
                        '</div>',
                        '<div class="stats-row">',
                            '<div class="attribute-label">Armor</div>',
                            '<div class="attribute-value">{stats.armor}',
                                '<tpl if="statDeltas.armor">',
                                    '<tpl if="statDeltas.armor &gt; 0">',
                                        '<span class="change d3-color-green">+{statDeltas.armor}</span>',
                                    '<tpl else>',
                                        '<span class="change d3-color-red">{statDeltas.armor}</span>',
                                    '</tpl>',
                                '</tpl>',
                            '</div>',
                        '</div>',
                    '</div>',

                    '<div class="stats-group">',
                        '<div class="stats-row">',
                            '<div class="attribute-label">Strength</div>',
                            '<div class="attribute-value">{stats.strength}',
                                '<tpl if="statDeltas.strength">',
                                    '<tpl if="statDeltas.strength &gt; 0">',
                                        '<span class="change d3-color-green">+{statDeltas.strength}</span>',
                                    '<tpl else>',
                                        '<span class="change d3-color-red">{statDeltas.strength}</span>',
                                    '</tpl>',
                                '</tpl>',
                            '</div>',
                        '</div>',
                        '<div class="stats-row">',
                            '<div class="attribute-label">Dexterity</div>',
                            '<div class="attribute-value">{stats.dexterity}',
                                '<tpl if="statDeltas.dexterity">',
                                    '<tpl if="statDeltas.dexterity &gt; 0">',
                                        '<span class="change d3-color-green">+{statDeltas.dexterity}</span>',
                                    '<tpl else>',
                                        '<span class="change d3-color-red">{statDeltas.dexterity}</span>',
                                    '</tpl>',
                                '</tpl>',
                            '</div>',
                        '</div>',
                        '<div class="stats-row">',
                            '<div class="attribute-label">Intelligence</div>',
                            '<div class="attribute-value">{stats.intelligence}',
                                '<tpl if="statDeltas.intelligence">',
                                    '<tpl if="statDeltas.intelligence &gt; 0">',
                                        '<span class="change d3-color-green">+{statDeltas.intelligence}</span>',
                                    '<tpl else>',
                                        '<span class="change d3-color-red">{statDeltas.intelligence}</span>',
                                    '</tpl>',
                                '</tpl>',
                            '</div>',
                        '</div>',
                        '<div class="stats-row">',
                            '<div class="attribute-label">Vitality</div>',
                            '<div class="attribute-value">{stats.vitality}',
                                '<tpl if="statDeltas.vitality">',
                                    '<tpl if="statDeltas.vitality &gt; 0">',
                                        '<span class="change d3-color-green">+{statDeltas.vitality}</span>',
                                    '<tpl else>',
                                        '<span class="change d3-color-red">{statDeltas.vitality}</span>',
                                    '</tpl>',
                                '</tpl>',
                            '</div>',
                        '</div>',
                        '<div class="stats-row">',
                            '<div class="attribute-label">Special Resource</div>',
                            '<div class="attribute-value">{stats.primaryResource}',
                                '<tpl if="statDeltas.primaryResource">',
                                    '<tpl if="statDeltas.primaryResource &gt; 0">',
                                        '<span class="change d3-color-green">+{statDeltas.primaryResource}</span>',
                                    '<tpl else>',
                                        '<span class="change d3-color-red">{statDeltas.primaryResource}</span>',
                                    '</tpl>',
                                '</tpl>',
                            '</div>',
                        '</div>',
                    '</div>',

                    '<div class="stats-group">',
                        '<div class="stats-row">',
                            '<div class="attribute-label">Attack Speed</div>',
                            '<div class="attribute-value">{[values.stats.attackSpeed.toFixed(2)]}',
                                '<tpl if="statDeltas.attackSpeed">',
                                    '<tpl if="statDeltas.attackSpeed &gt; 0">',
                                        '<span class="change d3-color-green">+{[values.statDeltas.attackSpeed.toFixed(2)]}</span>',
                                    '<tpl else>',
                                        '<span class="change d3-color-red">{[values.statDeltas.attackSpeed.toFixed(2)]}</span>',
                                    '</tpl>',
                                '</tpl>',
                            '</div>',
                        '</div>',
                        '<div class="stats-row">',
                            '<div class="attribute-label">Critical Hit Chance</div>',
                            '<div class="attribute-value">{[(values.stats.critChance * 100).toFixed(1)]}%',
                                '<tpl if="statDeltas.critChance">',
                                    '<tpl if="statDeltas.critChance &gt; 0">',
                                        '<span class="change d3-color-green">+{[(values.statDeltas.critChance * 100).toFixed(1)]}%</span>',
                                    '<tpl else>',
                                        '<span class="change d3-color-red">{[(values.statDeltas.critChance * 100).toFixed(1)]}%</span>',
                                    '</tpl>',
                                '</tpl>',
                            '</div>',
                        '</div>',
                        '<div class="stats-row">',
                            '<div class="attribute-label">Critical Hit Damage</div>',
                            '<div class="attribute-value">{[(values.stats.critDamage * 100).toFixed(1)]}%',
                                '<tpl if="statDeltas.critDamage">',
                                    '<tpl if="statDeltas.critDamage &gt; 0">',
                                        '<span class="change d3-color-green">+{[(values.statDeltas.critDamage * 100).toFixed(1)]}%</span>',
                                    '<tpl else>',
                                        '<span class="change d3-color-red">{[(values.statDeltas.critDamage * 100).toFixed(1)]}%</span>',
                                    '</tpl>',
                                '</tpl>',
                            '</div>',
                        '</div>',
                        '<div class="stats-row">',
                            '<div class="attribute-label">Damage Increase</div>',
                            '<div class="attribute-value">{[(values.stats.damageIncrease * 100).toFixed(0)]}%',
                                '<tpl if="statDeltas.damageIncrease">',
                                    '<tpl if="statDeltas.damageIncrease &gt; 0">',
                                        '<span class="change d3-color-green">+{[(values.statDeltas.damageIncrease * 100).toFixed(0)]}%</span>',
                                    '<tpl else>',
                                        '<span class="change d3-color-red">{[(values.statDeltas.damageIncrease * 100).toFixed(0)]}%</span>',
                                    '</tpl>',
                                '</tpl>',
                            '</div>',
                        '</div>',
                    '</div>',

                    '<div class="stats-group">',
                        '<div class="stats-row">',
                            '<div class="attribute-label">Damage Reduction</div>',
                            '<div class="attribute-value">{[(values.stats.damageReduction * 100).toFixed(2)]}%',
                                '<tpl if="statDeltas.damageReduction">',
                                    '<tpl if="statDeltas.damageReduction &gt; 0">',
                                        '<span class="change d3-color-green">+{[(values.statDeltas.damageReduction * 100).toFixed(2)]}%</span>',
                                    '<tpl else>',
                                        '<span class="change d3-color-red">{[(values.statDeltas.damageReduction * 100).toFixed(2)]}%</span>',
                                    '</tpl>',
                                '</tpl>',
                            '</div>',
                        '</div>',
                        '<div class="stats-row">',
                            '<div class="attribute-label">Life on Hit</div>',
                            '<div class="attribute-value">{[values.stats.lifeOnHit.toFixed(0)]}',
                                '<tpl if="statDeltas.lifeOnHit">',
                                    '<tpl if="statDeltas.lifeOnHit &gt; 0">',
                                        '<span class="change d3-color-green">+{[values.statDeltas.lifeOnHit.toFixed(0)]}</span>',
                                    '<tpl else>',
                                        '<span class="change d3-color-red">{[values.statDeltas.lifeOnHit.toFixed(0)]}</span>',
                                    '</tpl>',
                                '</tpl>',
                            '</div>',
                        '</div>',
                        '<div class="stats-row">',
                            '<div class="attribute-label">Life per Kill</div>',
                            '<div class="attribute-value">{[values.stats.lifePerKill.toFixed(0)]}',
                                '<tpl if="statDeltas.lifePerKill">',
                                    '<tpl if="statDeltas.lifePerKill &gt; 0">',
                                        '<span class="change d3-color-green">+{[values.statDeltas.lifePerKill.toFixed(0)]}</span>',
                                    '<tpl else>',
                                        '<span class="change d3-color-red">{[values.statDeltas.lifePerKill.toFixed(0)]}</span>',
                                    '</tpl>',
                                '</tpl>',
                            '</div>',
                        '</div>',
                        '<div class="stats-row">',
                            '<div class="attribute-label">Life Steal</div>',
                            '<div class="attribute-value">{[(values.stats.lifeSteal * 100).toFixed(0)]}%',
                                '<tpl if="statDeltas.lifeSteal">',
                                    '<tpl if="statDeltas.lifeSteal &gt; 0">',
                                        '<span class="change d3-color-green">+{[(values.statDeltas.lifeSteal * 100).toFixed(0)]}%</span>',
                                    '<tpl else>',
                                        '<span class="change d3-color-red">{[(values.statDeltas.lifeSteal * 100).toFixed(0)]}%</span>',
                                    '</tpl>',
                                '</tpl>',
                            '</div>',
                        '</div>',
                        '<div class="stats-row">',
                            '<div class="attribute-label">Block Chance</div>',
                            '<div class="attribute-value">{[(values.stats.blockChance * 100).toFixed(2)]}%',
                                '<tpl if="statDeltas.blockChance">',
                                    '<tpl if="statDeltas.blockChance &gt; 0">',
                                        '<span class="change d3-color-green">+{[(values.statDeltas.blockChance * 100).toFixed(2)]}%</span>',
                                    '<tpl else>',
                                        '<span class="change d3-color-red">{[(values.statDeltas.blockChance * 100).toFixed(2)]}%</span>',
                                    '</tpl>',
                                '</tpl>',
                            '</div>',
                        '</div>',
                    '</div>',

                    // highlight the biggest resist
                    '<div class="stats-group">',
                        '<div class="stats-row">',
                            '<div class="attribute-label">Arcane Resist</div>',
                            '<div class="attribute-value">{stats.arcaneResist}',
                                '<tpl if="statDeltas.arcaneResist">',
                                    '<tpl if="statDeltas.arcaneResist &gt; 0">',
                                        '<span class="change d3-color-green">+{statDeltas.arcaneResist}</span>',
                                    '<tpl else>',
                                        '<span class="change d3-color-red">{statDeltas.arcaneResist}</span>',
                                    '</tpl>',
                                '</tpl>',
                            '</div>',
                        '</div>',
                        '<div class="stats-row">',
                            '<div class="attribute-label">Cold Resist</div>',
                            '<div class="attribute-value">{stats.coldResist}',
                                '<tpl if="statDeltas.coldResist">',
                                    '<tpl if="statDeltas.coldResist &gt; 0">',
                                        '<span class="change d3-color-green">+{statDeltas.coldResist}</span>',
                                    '<tpl else>',
                                        '<span class="change d3-color-red">{statDeltas.coldResist}</span>',
                                    '</tpl>',
                                '</tpl>',
                            '</div>',
                        '</div>',
                        '<div class="stats-row">',
                            '<div class="attribute-label">Fire Resist</div>',
                            '<div class="attribute-value">{stats.fireResist}',
                                '<tpl if="statDeltas.fireResist">',
                                    '<tpl if="statDeltas.fireResist &gt; 0">',
                                        '<span class="change d3-color-green">+{statDeltas.fireResist}</span>',
                                    '<tpl else>',
                                        '<span class="change d3-color-red">{statDeltas.fireResist}</span>',
                                    '</tpl>',
                                '</tpl>',
                            '</div>',
                        '</div>',
                        '<div class="stats-row">',
                            '<div class="attribute-label">Lightning Resist</div>',
                            '<div class="attribute-value">{stats.lightningResist}',
                                '<tpl if="statDeltas.lightningResist">',
                                    '<tpl if="statDeltas.lightningResist &gt; 0">',
                                        '<span class="change d3-color-green">+{statDeltas.lightningResist}</span>',
                                    '<tpl else>',
                                        '<span class="change d3-color-red">{statDeltas.lightningResist}</span>',
                                    '</tpl>',
                                '</tpl>',
                            '</div>',
                        '</div>',
                        '<div class="stats-row">',
                            '<div class="attribute-label">Poison Resist</div>',
                            '<div class="attribute-value">{stats.poisonResist}',
                                '<tpl if="statDeltas.poisonResist">',
                                    '<tpl if="statDeltas.poisonResist &gt; 0">',
                                        '<span class="change d3-color-green">+{statDeltas.poisonResist}</span>',
                                    '<tpl else>',
                                        '<span class="change d3-color-red">{statDeltas.poisonResist}</span>',
                                    '</tpl>',
                                '</tpl>',
                            '</div>',
                        '</div>',
                    '</div>',

                    // convert these to a %
                    '<div class="stats-group">',
                        '<div class="stats-row">',
                            '<div class="attribute-label">Magic Find</div>',
                            '<div class="attribute-value">{[(values.stats.magicFind * 100).toFixed(0)]}%',
                                '<tpl if="statDeltas.magicFind">',
                                    '<tpl if="statDeltas.magicFind &gt; 0">',
                                        '<span class="change d3-color-green">+{[(values.statDeltas.magicFind * 100).toFixed(0)]}%</span>',
                                    '<tpl else>',
                                        '<span class="change d3-color-red">{[(values.statDeltas.magicFind * 100).toFixed(0)]}%</span>',
                                    '</tpl>',
                                '</tpl>',
                            '</div>',
                        '</div>',
                        '<div class="stats-row">',
                            '<div class="attribute-label">Gold Find</div>',
                            '<div class="attribute-value">{[(values.stats.goldFind * 100).toFixed(0)]}%',
                                '<tpl if="statDeltas.goldFind">',
                                    '<tpl if="statDeltas.goldFind &gt; 0">',
                                        '<span class="change d3-color-green">+{[(values.statDeltas.goldFind * 100).toFixed(0)]}%</span>',
                                    '<tpl else>',
                                        '<span class="change d3-color-red">{[(values.statDeltas.goldFind * 100).toFixed(0)]}%</span>',
                                    '</tpl>',
                                '</tpl>',
                            '</div>',
                        '</div>',
                    '</div>',

                '</div>',
            '</div>'
        )
    },
    initialize : function() {
        var me = this;
//        me.add(me.getHeader());
        me.setData(me.getData());
        me.callParent();
    },
    applyHeader : function(cfg, inst) {
        if (!inst) {
            Ext.apply(cfg,
                {
                    data : Ext.apply(this.getData(), {
                            headerLabel : this.getHeaderLabel()
                        })
                }
            );
        }
        return Ext.factory(cfg, D3Mobile.view.hero.Header, inst);
    }


});